const MAX_BUNDLE_SIZE_LIMIT_MOBILE = 10
const MAX_BUNDLE_SIZE_LIMIT_PRIMEDATE = 10
const MAX_BUNDLE_SIZE_LIMIT_FRONTEND = 10
const MAX_BUNDLE_SIZE_LIMIT_LMS = 10

const MOBILE = 'mobile'
const PRIMEDATE = 'primedate'
const FRONTEND = 'frontend'
const LMS = 'lms'

exports.MAX_BUNDLE_SIZE_LIMIT_MOBILE = MAX_BUNDLE_SIZE_LIMIT_MOBILE
exports.MAX_BUNDLE_SIZE_LIMIT_PRIMEDATE = MAX_BUNDLE_SIZE_LIMIT_PRIMEDATE
exports.MAX_BUNDLE_SIZE_LIMIT_FRONTEND = MAX_BUNDLE_SIZE_LIMIT_FRONTEND
exports.MAX_BUNDLE_SIZE_LIMIT_LMS = MAX_BUNDLE_SIZE_LIMIT_LMS

exports.MOBILE = MOBILE
exports.PRIMEDATE = PRIMEDATE
exports.FRONTEND = FRONTEND
exports.LMS = LMS
